- src/core/initAligningGuidelines.js
fix https://github.com/nihaojob/vue-fabric-editor/issues/66
> fix: 缩放后辅助线未对齐

- index.html
- src/components/color.vue
解决渐变色选中的时候，多滚动条（给html添加了overflow:none），以及渐变色弹框闪动(渐变色组件内部不好控制（使用功能v-if，v-show控制渐变组件，或者修改外边定位，都会导致渐变组件部分功能失效），目前外部使用透明度控制渐变色组件的弹框显隐)问题。
>  fix(gradient color): 解决渐变色元素选中的时候，渐变色弹框显隐问题。

- src/components/dragMode.vue
按照大多数的编辑器软件，普遍用户都习惯于按住空格来进行拖拽视图，所以我添加了一段小小的代码，支持按住空格进行拖拽😊
> feat(拖拽): 添加空格切换拖拽状态

- src/components/align.vue
> fix: :bug: 移除导致 `unplugin-auto-import` 自动引入不正常解析的注释

- packages/core/core.ts
解决 listener 为 undefined 的时候卸载错误
> 解决 listener 为 undefined 的时候卸载错误

- tsconfig.json
解决在 webstorm 下使用别名 @ 导入包没有代码提示
> 解决在 webstorm 下使用别名没提示

- .gitignore
- package.json
- packages/core/package.json
- packages/core/vite.config.ts
1：将package.json的npm改为pnpm, 使用了pnpm作为monorepo，就需要pnpm安装依赖，不然package/core依赖可能有问题
2：优化打包命令，将sdk打包的vite.config.ts移到对应项目， build:sdk时直接执行package/core的build命令
> chore: 优化sdk打包命令

- packages/core/Editor.ts
- src/views/home/index.vue
Editor 需要一个销毁函数，组件卸载的时候用来销毁Editor。之后单元测试，也能方便销毁测试Editor实例。
因为代理API是直接通过[]方式来代理，销毁函数暂时没法销毁通过代理API的数据
> fix(Editor): 增加Editor销毁函数

- src/components/waterMark.vue
修复[issue#357](https://github.com/nihaojob/vue-fabric-editor/issues/357)
出现问题的原因：点击遮罩或Modal的关闭按钮都会触发Modal组件的on-cancel事件，所以不应在on-cancel中清除水印。
本次提交的改动：
1.清除水印和渲染水印的按钮改成插槽，自定义Modal框的footer内容
2.水印名称必填项添加红色*号作为必填标识
> fix: 修复配置水印触发清除问题

- src/components/imgStroke.vue
修复[issue#360](https://github.com/nihaojob/vue-fabric-editor/issues/360)
出现这个问题的原因是：获取画布选中元素时，使用了computed计算getActiveObjects()的值，导致获取的选中元素不是最新的。
本次提交的改动：
监听selectOne事件，保证每次获取到正确的选中元素。
> fix: 修复点击切换元素时图像描边错误展示

- src/components/bgBar.vue
- src/components/waterMark.vue
修复[issue#362](https://github.com/nihaojob/vue-fabric-editor/issues/362)
经过排查发现是view ui plus的bug：当ColorPicker使用transfer属性时就会出现手动设置颜色失效
本次提交的改动：
1.删除transfer属性
2.右侧的ColorPicker不使用transfer会有样式问题，需要调整样式
> fix: 修复ColorPicker设置颜色失效

- packages/core/ServersPlugin.ts
修复[issue#369](https://github.com/nihaojob/vue-fabric-editor/issues/369)
原因是模板的图片少了id。
在导入模板或文件时，先预处理，如果元素没有id，则加上唯一id。
> fix: 修复元素与图层无法对应的问题

- packages/core/objects/Arrow.js
修复[issue#372](https://github.com/nihaojob/vue-fabric-editor/issues/372)
> fix: 修复箭头放缩变形及比例不一致的问题

- packages/core/Editor.ts
> 解决 pluginRunTime.pluginName 是 undefined

- packages/core/objects/ThinTailArrow.js
- packages/core/plugin/DrawLinePlugin.ts
- src/components/attribute.vue
- src/components/tools.vue
实现[issue#381](https://github.com/nihaojob/vue-fabric-editor/issues/381)
可以正常绘制，并且支持拖拽控制条时保持箭头不变形，具体效果：
> feat: 新增细尾箭头绘制元素(thinTailArrow)

- packages/core/plugin/WaterMarkPlugin.ts
修复[issue#384](https://github.com/nihaojob/vue-fabric-editor/issues/384)
出现问题的原因是：
1.使用measureText获取文本长度时没有考虑字体大小
2.计算patternCanvas的宽高时只是加或乘固定的数值，导致计算不准
本次提交已解决上述问题
> fix: 修复水印展示不全

- src/components/fontStyle.vue
- src/components/importSvgEl.vue
- src/components/tools.vue
- src/hooks/useCalculate.js
修复[issue#390](https://github.com/nihaojob/vue-fabric-editor/issues/390)
本次提交的改动：dragend事件拿到拖拽结束点，如果不在画布内，直接return
> fix: 修复元素拖拽上图没有判断画布区域的问题

- src/components/tools.vue
添加默认文字颜色 避免初始化rgb(0, 0, 0)颜色影响colorpikcer组件的正常显示
> fix: 解决默认文字颜色无法选中问题

- packages/core/plugin/FreeDrawPlugin.ts
- packages/core/plugin/PathTextPlugin.ts
修复[issue#415](https://github.com/nihaojob/vue-fabric-editor/issues/415)
出现问题的原因是没有设置绘制元素的唯一id
> fix: pathText和freeDraw元素绘制时设置唯一id

- packages/core/ServersPlugin.ts
- packages/core/plugin/PathTextPlugin.ts
- src/components/attributeTextContent.vue
修复[issue#417](https://github.com/nihaojob/vue-fabric-editor/issues/417)
加载json回显失败，有两层原因：路径回显失败、文字回显失败
- 针对路径回显失败，做了以下改动：
1.将绘制的元素由fabric.Text改为fabric.IText
2.加载json时先忽略path属性，上图后再加上
- 针对文字回显失败，做了以下改动
在绘制时设置fontFamily
> fix: 修复路径文本元素导入json失败

- src/components/tools.vue
修复[issue#420](https://github.com/nihaojob/vue-fabric-editor/issues/420)
> fix: 绘制元素状态退出

- src/components/imgStroke.vue
> fix(stroke): 修复描边色彩选择器位置

- packages/core/plugin/ResizePlugin.ts
解决拖拽画布居中后，出现的以下问题：
1.拖拽时鼠标光标闪烁的问题
2.拖拽时控制条闪烁的问题
3.拖拽时控制条位置没有与鼠标同步
> fix(plugin): resize插件拖拽适配画布居中

- packages/core/plugin/LayerPlugin.ts
- packages/core/plugin/ResizePlugin.ts
- packages/core/plugin/WorkspacePlugin.ts
- src/views/home/index.vue
新增功能workspace外加入蒙层。
已完成layer插件，resize插件以及模板和psd的loadjson的适配工作。
src/views/home/index.vue中默认打开了蒙层，注释掉
```
canvasEditor.getPlugin('WorkspacePlugin').maskEnable();
```
即可关闭蒙层功能
关联issues #468
> feat(core): workspace加入蒙层功能，已考虑layer，resize和loadjson的适配

- src/components/align.vue
代码层面的调整，不涉及功能改动：
1.去掉多余class声明
2.vite-svg-loader默认以vue组件方式引入，所以可以去掉 *?component* 后缀
> refactor: 调整svg图标引入

- packages/core/ServersPlugin.ts
- packages/core/index.ts
- packages/core/objects/CustomRect.js
- src/components/attributeRounded.vue
解决issue #495 
原因是圆角展示受到rx、ry属性及元素放缩的共同影响；
如果在元素外部解决此问题，需要在设置圆角时做适配，并且元素放缩时也要监听进行圆角调整，略显麻烦。
解决方案：扩展fabric.Rect类，在Rect元素内部解决
> fix: 矩形圆角适配拖拽放缩

- packages/core/plugin/CenterAlignPlugin.ts
- packages/core/plugin/DeleteHotKeyPlugin.ts
- packages/core/plugin/FlipPlugin.ts
- src/language/zh.json
问题：右键菜单中‘删除’和’水平垂直居中‘’快捷键都是Ctr+V
修改后：
问题2：右键翻转的国际化显示错误
修复后：
> fix(右键菜单): 右键菜单显示快捷建错误问题修复

- package.json
- [ x ] 代码构建正常
写入你的修改内容。
间接依赖 `@jridgewell/source-map@0.3.6` 存在问题
https://github.com/jridgewell/sourcemaps/issues/6
> fix: @jridgewell/source-map@0.3.6 deps error

- packages/core/plugin/LockPlugin.ts
处理元素锁定后多选会被移动的问题
禁止锁定的元素被多选命中，包含左键拖拽多选以及shift+左键点击多选的情况
> feat: 对象锁定状态下禁止被多选
