ikuaitu/vue-fabric-editor

src/components/history.vue
src/core/hotkeys/backspace.js
src/core/hotkeys/ctrlz.js
src/core/hotkeys/lrdu.js
src/plugin/EventBus/index.js
src/plugin/eventbus.js
src/plugin/hotkeys.js
src/views/HomeView.vue

hotkeys监听ctrl+z，再通过eventbus触发history组件的undo

feat: 快捷键回退功能

---

src/App.vue
src/components/mouseMenu.vue
src/views/home/index.vue

feat(功能完善): 右键菜单功能

---

.eslintrc.js
src/components/contextMenu/index.vue
src/components/contextMenu/menuItem.vue
src/core/initHotKeys.js
src/locales/lang/en.json
src/locales/lang/pt.json
src/locales/lang/zh.json
src/views/home/index.vue

* feat(功能完善): 右键菜单功能
* feat(功能完善): 右键菜单功能 (#42)
* fix: 右键菜单复制优化
* fix: 快捷键复制优化
* fix: 注释
* 强制合并
* fix(功能优化): 右键菜单功能优化
* feat: 右键二级菜单 ---------
Co-authored-by: 秦少卫 <nihaojob@163.com>

fix: 右键菜单优化 (#61)

---

src/views/home/index.vue

#62 添加背景层和标尺 由于我的项目是用Konvajs + ts 写的 所以 js事件部分就没有上传代码了 希望你能补全一下
似乎我的eslint 会自动修复冒号等问题 希望不要介意

feat(bolg): 添加背景层 添加辅助标尺

---

src/core/EditorWorkspace.js

fix(workspace): 修复调整窗口大小画布元素错乱问题

---

src/core/index.js

fix(editor): 修复进行一次撤销操作后，背景图层可以进行删除问题

---

src/components/history.vue

feat(history): 增加画布元素数量变化记录到历史记录和修复回退bug

---

.gitignore
src/components/layer.vue
src/components/tools.vue
src/core/initAligningGuidelines.js
src/core/ruler/guideline.ts
src/core/ruler/index.ts
src/core/ruler/ruler.ts
src/core/ruler/type.d.ts
src/core/ruler/utils.ts
src/utils/eventHandler.js

feat: 标尺增加刻度显示

---

src/core/initControls.js

https://user-images.githubusercontent.com/48149577/230894406-bd3c6869-dc43-4e90-a14f-8be88f52b3bd.mov

fix(deleteObject): delete control triggering during object rotation

---

package.json
src/utils/local.ts
src/utils/utils.ts

* feat(typescript): 升级到版本 5，支持装饰器
* feat(typescript): /src/utils 转换成 ts 文件
* Delete eventHandler.ts
* fix(TS): 合并代码问题
---------

Feat typescript update (#161)

---

src/components/save.vue
src/language/en.json
src/language/zh.json

fix(清空确认): 增加清空按钮二次确认

---

src/core/initAligningGuidelines.ts
tsconfig.json
typings/extends.d.ts

feat: convert core/initAligningGuidelines to TS

---

package.json
src/components/attribute.vue
src/components/color.vue
src/components/inputNumber/index.ts
src/components/inputNumber/inputNumber.vue
src/core/ruler/utils.ts

添加了滑动修改，顺便把arco design的上下快捷键和长按搬过来了。

feat: 新的inputNumber，支持滑动修改

---

.gitignore
src/components/attribute.vue

feat: 字体下拉列表增加预览图片

---

src/components/setSize.vue
src/hooks/useI18n.js

refactor(国际化): i18n国际化提取为hook
refactor(setSize组件): setSize组件修改为set形式
自测：

Big face2019 refactor set size

---

package.json
src/components/save.vue
src/utils/utils.ts

feat: downloadjs

---

src/components/setSize.vue
src/language/en.json
src/language/zh.json

fix: 弹窗修改尺寸

---

src/core/index.ts
src/core/plugin/FlipPlugin.ts
src/language/index.ts
src/utils/event/notifier.ts
src/views/home/index.vue

feat: add flip plugin & change select event to singleton

---

src/components/colorSelector.vue

fix: 渐变组件点击位置错误问题

---

package.json
src/components/colorSelector.vue

fix: 渐变回调优化

---

src/core/ServersPlugin.ts
src/core/core.ts
src/core/plugin/GroupPlugin.ts
src/core/plugin/HistoryPlugin.ts
src/core/plugin/WorkspacePlugin.ts

1. Add '⌘' undo|redo hotkeys to support mac keyboard.
2. Fix undo render logic issue.

Feat: Add '⌘' undo|redo hotkeys to support mac keyboard; 2. Fix undo logic  issue

---

src/core/plugin/CopyPlugin.ts
src/core/plugin/DownFontPlugin.ts

just test pr--（Improve ts syntax issues）

fix: dev-pr

---

src/views/home/index.vue

fix: 修复左侧显示隐藏工具按钮

---

packages/core/plugin/AlignGuidLinePlugin.ts

fix 保存图片时报错

---

packages/core/ServersPlugin.ts

给 insertSvgFile 添加回调处理方便添加类似隐藏进度条，加载成功之类的情况

给 insertSvgFile 添加回调处理

---

packages/core/plugin/GroupTextEditorPlugin.ts

fix(组合文字): 组合文字缩放后，第一次编辑文字依然是缩放前的大小

---

packages/core/plugin/CopyPlugin.ts

feat: 从浏览器外部复制粘文本、图片、svg文件到画布

---

src/components/waterMark.vue
src/language/en.json
src/language/zh.json

feat: 清除水印

---

package.json

ts v5.1.6 比 v4.9.5 支持更友好，也能抑制如下警告
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.2.0
YOUR TYPESCRIPT VERSION: 5.4.5
Please only submit bug reports when using the officially supported version.

chore(依赖): 固定ts v5.1.6，消除终端告警&增强ts功能

---

src/components/bgBar.vue

修复[issue#353](https://github.com/nihaojob/vue-fabric-editor/issues/353)

fix: 修复右侧配色板语言切换失效

---

packages/core/ServersPlugin.ts
src/components/bgBar.vue

修复[issue#366](https://github.com/nihaojob/vue-fabric-editor/issues/366)

fix: 修改右侧背景色框回填

---

src/components/colorSelector.vue

防止从模板加载后出现colorStops报错
写入你的修改内容。

fix: 防止从模板加载后出现colorStops报错

---

src/components/colorSelector.vue

fix: eslint检测缺少分号

---

src/components/attribute.vue

修复[issue#375](https://github.com/nihaojob/vue-fabric-editor/issues/375)

fix: 修复边框属性值回填问题

---

packages/core/Editor.ts

hook 兼容非 Promise 返回值

---

packages/core/plugin/FontPlugin.ts

修复[issue#392](https://github.com/nihaojob/vue-fabric-editor/issues/392)

fix: 修复字体列表重复请求问题

---

packages/core/plugin/PolygonModifyPlugin.ts

fix: 恢复patch

---

packages/core/plugin/GroupAlignPlugin.ts

没有冲突
修复组内如果有对象旋转后水平分布和垂直分布分布不均匀的问题

fix: 当对象旋转后水平分布和垂直分布不均匀的问题

---

packages/core/__tests__/env.d.ts
packages/core/__tests__/plugin/DringPlugin.spec.ts
packages/core/__tests__/utils/common.ts
packages/core/__tests__/utils/setup.ts
packages/core/plugin/DringPlugin.ts
packages/core/vitest.config.ts

feat(tests): 增加插件测试

---

src/components/attributePostion.vue
src/language/en.json
src/language/zh.json

feat: 新增矩形圆角属性功能

---

src/components/attributePostion.vue
src/components/attributeRounded.vue
src/language/en.json
src/language/pt.json
src/language/zh.json
src/views/home/index.vue

新增矩形圆角功能，仅对矩形作用

---

typings/env.d.ts
typings/extends.d.ts

fix: 增加类型定义

---

packages/core/plugin/SimpleClipImagePlugin.ts

fix: 修复圆形裁切调整上下左右缩放成椭圆时，取消选择回复圆的问题

---

packages/core/plugin/CopyPlugin.ts

fix: 修复画布内外复制粘贴重复问题

---

src/views/home/index.vue

修复vue-i18n function 't' 在ref函数中不生效的问题
详细参考：https://github.com/intlify/vue-i18n/issues/1396

fix: 修复vue-i18n function 't' 在ref函数中不生效的问题

---

src/components/lang.vue
src/views/home/index.vue

fix: 修复界面交互问题

---

packages/core/index.ts
packages/core/plugin/ResizePlugin.ts
packages/core/styles/resizePlugin.css
src/views/home/index.vue

实现issue #251 ，新增画布resize拖拽功能
https://github.com/nihaojob/vue-fabric-editor/assets/63847336/8921ce79-499a-4bf5-b0a6-17b475941861

feat: 新增画布resize拖拽插件

---

packages/core/plugin/PsdPlugin.ts

add callback for psd plugin

---

packages/core/ServersPlugin.ts
packages/core/utils/utils.ts
src/components/save.vue

移除@kuaitu/core中viewui的使用
消息提示移交至业务层
[#459 ](https://github.com/nihaojob/vue-fabric-editor/issues/459)

fix(#459): @kuaitu/core中移除viewui的使用，消息提示移交至业务层

---

packages/core/plugin/PolygonModifyPlugin.ts

之前提交解决过 #397 ，不过被后续其他PR覆盖了，再次恢复下

fix: 再次恢复patch397

---

packages/core/plugin/WorkspacePlugin.ts

fix(plugin): 优化workspacePlugin的resize功能

---

packages/core/ServersPlugin.ts
packages/core/plugin/GroupPlugin.ts
src/components/attributeBorder.vue

fix: 隐藏组元素描边选项

---

packages/core/index.ts
packages/core/plugin/LayerPlugin.ts
packages/core/plugin/MaskPlugin.ts
packages/core/plugin/ResizePlugin.ts
packages/core/plugin/WorkspacePlugin.ts
src/views/home/index.vue

已改为插件形式，并优化了原先裁剪的逻辑，均使用事件形式，统一处理
关联issue #468

feat(core): 添加蒙层插件

---

packages/core/plugin/PolygonModifyPlugin.ts

fix(plugin): 修复多边形编辑失效问题

---

packages/core/plugin/HistoryPlugin.ts
src/components/save.vue

fix: 修复清空画布时，历史记录没有清空问题

---

packages/core/ServersPlugin.ts
src/components/common/masonry.vue
src/components/importTmpl.vue
src/hooks/pageList.js

feat(component): 素材瀑布流布局

---

.vscode/extensions.json

chore: 添加i8n ally扩展推荐

---

.vscode/extensions.json

chore: 添加代码格式化插件扩展推荐

---

packages/core/plugin/AddBaseTypePlugin.ts
packages/core/plugin/BarCodePlugin.ts
packages/core/plugin/DrawLinePlugin.ts
packages/core/plugin/HistoryPlugin.ts
packages/core/plugin/QrCodePlugin.ts

修改了AddBaseTypePlugin.ts、BarCodePlugin.ts、DrawLinePlugin.ts、HistoryPlugin.ts、QrCodelugin.ts

fix(修复撤销功能): 修复了撤销按钮无法撤销画布数据的bug
